context:
  version: 3.1.0

package:
  name: inject-markdown
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/inject-markdown/-/inject-markdown-${{ version }}.tgz
  sha256: 6603f48191bb8e3772a40268702cc13b18668b64a049c9995d11db485c5d036c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - inject-markdown --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Tool to inject files into markdown files.
  homepage: https://github.com/streetsidesoftware/inject-markdown
  repository: https://github.com/streetsidesoftware/inject-markdown

extra:
  recipe-maintainers:
    - danielnachun
