context:
  version: "5.0.3"

package:
  name: inject-markdown
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/inject-markdown/-/inject-markdown-${{ version }}.tgz
  sha256: 7fc1414c07673f492812ef96b34d3e3660594eb3b9bfd3e22659f7e82a33f4df

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - inject-markdown --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Tool to inject files into markdown files.
  homepage: https://github.com/streetsidesoftware/inject-markdown
  repository: https://github.com/streetsidesoftware/inject-markdown

extra:
  recipe-maintainers:
    - danielnachun
